"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.V10 = exports.V9 = exports.V8 = exports.V7 = exports.V6 = exports.V5 = exports.V4 = exports.V3 = exports.V2 = exports.V1 = exports.Vzero = void 0;
exports.Vzero = [null];
exports.V1 = [exports.Vzero];
exports.V2 = [exports.V1];
exports.V3 = [exports.V2];
exports.V4 = [exports.V3];
exports.V5 = [exports.V4];
exports.V6 = [exports.V5];
exports.V7 = [exports.V6];
exports.V8 = [exports.V7];
exports.V9 = [exports.V8];
exports.V10 = [exports.V9];
